-- Generated by xghost. Do not edit.
-- Run 'xghost theme set <name>' to rebuild this file.
--
-- The palette of the active theme, for the prescribed Lua beside it to read.
-- config/nvim/lua/config/xghost.lua names these colours and defines none of its
-- own, because this file is the half that follows the theme and that file is
-- the half that decides which highlight group each colour reaches.
--
-- This file is data in the shape of a Lua module. It declares a table and
-- returns it. It calls nothing, it requires nothing, and it reads no state of
-- the editor, so loading it can only produce the table below.
--
-- Every value is the plain form: the colour exactly as the theme declares it.
-- Neovim wants '#rrggbb' and nothing else, so the two derived forms of
-- docs/theming.md reach no line here.

return {
	bg = "#1A1B26",
	surface = "#1F2335",
	surface_alt = "#1A1B26",
	text = "#C0CAF5",
	text_muted = "#A9B1D6",
	accent = "#7AA2F7",
	accent_alt = "#73DACA",
	warn = "#E0AF68",
	error = "#F7768E",
	success = "#9ECE6A",
}
