-- Generated by xghost. Do not edit.
-- Run 'xghost theme set <name>' to rebuild this file.
--
-- The palette of the active theme, for the prescribed Lua beside it to read.
-- config/nvim/lua/config/xghost.lua names these colours and defines none of its
-- own, because this file is the half that follows the theme and that file is
-- the half that decides which highlight group each colour reaches.
--
-- This file is data in the shape of a Lua module. It declares a table and
-- returns it. It calls nothing, it requires nothing, and it reads no state of
-- the editor, so loading it can only produce the table below.
--
-- Every value is the plain form: the colour exactly as the theme declares it.
-- Neovim wants '#rrggbb' and nothing else, so the two derived forms of
-- docs/theming.md reach no line here.

return {
	bg = "#0f1115",
	surface = "#1c1f26",
	surface_alt = "#0f1115",
	text = "#e8e8ed",
	text_muted = "#a1a1aa",
	accent = "#0a84ff",
	accent_alt = "#64d2ff",
	warn = "#ffc934",
	error = "#ff453a",
	success = "#34c759",
}
