# Generated by xghost. Do not edit.
# Run 'xghost theme set <name>' to rebuild this file.
#
# The palette of the active theme, for a shell script to source. Each value is
# the plain form: the colour exactly as the theme declares it.

XGHOST_BG='#1A1B26'
XGHOST_SURFACE='#1F2335'
XGHOST_SURFACE_ALT='#1A1B26'
XGHOST_TEXT='#C0CAF5'
XGHOST_TEXT_MUTED='#A9B1D6'
XGHOST_ACCENT='#7AA2F7'
XGHOST_ACCENT_ALT='#73DACA'
XGHOST_WARN='#E0AF68'
XGHOST_ERROR='#F7768E'
XGHOST_SUCCESS='#9ECE6A'
