# Generated by xghost. Do not edit.
# Run 'xghost theme set <name>' to rebuild this file.
#
# The palette of the active theme, for a shell script to source. Each value is
# the plain form: the colour exactly as the theme declares it.

XGHOST_BG='@BG@'
XGHOST_SURFACE='@SURFACE@'
XGHOST_SURFACE_ALT='@SURFACE_ALT@'
XGHOST_TEXT='@TEXT@'
XGHOST_TEXT_MUTED='@TEXT_MUTED@'
XGHOST_ACCENT='@ACCENT@'
XGHOST_ACCENT_ALT='@ACCENT_ALT@'
XGHOST_WARN='@WARN@'
XGHOST_ERROR='@ERROR@'
XGHOST_SUCCESS='@SUCCESS@'
