# Generated by xghost. Do not edit.
# Run 'xghost theme set <name>' to rebuild this file.
#
# The palette of the active theme, for a shell script to source. Each value is
# the plain form: the colour exactly as the theme declares it.

XGHOST_BG='#0f1115'
XGHOST_SURFACE='#1c1f26'
XGHOST_SURFACE_ALT='#0f1115'
XGHOST_TEXT='#e8e8ed'
XGHOST_TEXT_MUTED='#a1a1aa'
XGHOST_ACCENT='#0a84ff'
XGHOST_ACCENT_ALT='#64d2ff'
XGHOST_WARN='#ffc934'
XGHOST_ERROR='#ff453a'
XGHOST_SUCCESS='#34c759'
